#!/bin/bash

for host in $(cat ~/contrail-ansible-deployer/config/all_hosts); do

(./config/sshpass -p contrail123 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -r \
/config \
/docker \
/www \
$host:/var/tmp) &

done
